s103071049/FAC-CAT-DESSERT

- src/components/App/App.js
- src/components/contexts/PageChange.js
- src/pages/SearchPage/SearchPage.js
- src/pages/SearchPage/components/SearchContextProduct.js
- src/pages/SearchPage/components/SearchItem.js
- src/pages/SearchPage/index.js
> serchPage切版

- src/components/App/App.js
- src/pages/Admin/OrderPage.js
- src/pages/Admin/components/OrderStatusFilter.js
- src/pages/Admin/components/OrderStatusSection.js
- src/pages/Admin/index.js
> test - admin/order merge to main

- src/components/App/App.js
- src/pages/TransactionPage/TransactionPage.js
- src/pages/UserPage/UserPage.js
merge user 的 訂單頁面 (transaction)
> merge transaction page to user page & and adjust app.js route

- src/WEBAPI.js
- src/components/App/App.js
- src/pages/SingleProductPage/SingleProductPage.js
> feat.singleProject資料渲染

- src/components/App/App.js
> cart route come back

- src/components/App/App.js
- src/components/Header/Header.js
- src/components/img/icon/menu.svg
> Rwd header 2

- src/components/Header/Header.js
- src/hooks/common/useHeader.js
> fix.電腦版header無法捲動問題

- src/pages/Admin/OrderPage.js
> fix.orders的useHeader路徑錯誤

- src/WEBAPI.js
- src/hooks/user/useTransaction.js
- src/pages/TransactionPage/TransactionPage.js
> Trasaction page function

- src/components/common/PageBtn.js
- src/hooks/common/usePagination.js
- src/hooks/productHooks/useAdminProducts.js
- src/hooks/productHooks/useAdminRestoreProducts.js
- src/hooks/productHooks/useFindProducts.js
- src/pages/AdminProductsPage/AdminProductsPage.js
- src/pages/AdminProductsRestorePage/AdminProductsRestorePage.js
- src/pages/ProductsPage/ProductsPage.js
- src/pages/ProductsPage/components/ProductsSection.js
修正了一些小bug，
還有分頁全部OK!
分頁請參考 `common/PageBtn.js` `hooks/common/usePagination.js`
在 product page 還有 admin restore product 和 admin products 我都有使用，可以去參考！
> Product pagination

- src/WEBAPI.js
- src/components/Header/Header.js
- src/hooks/common/useHeader.js
- src/hooks/user/useSingleTransaction.js
- src/hooks/user/useTransaction.js
- src/pages/SingleTransactionPage/SingleTransactionPage.js
- src/pages/SingleTransactionPage/index.js
- src/pages/TransactionPage/TransactionPage.js
- src/pages/UserPage/UserPage.js
抱歉混到 transaction 的 commit，請忽略`畫面凍結解決` 以上的 commit!
來了來了！
修好了！
onClick 加回去了，不然點其他頁面那個 rwd menu 會消失不了！
原因請看 `畫面凍結解決` 修改的檔案就會真相大白！
> Fix header rwd

- src/WEBAPI.js
- src/hooks/user/useSingleTransaction.js
- src/hooks/user/useTransaction.js
- src/pages/SingleTransactionPage/SingleTransactionPage.js
- src/pages/SingleTransactionPage/index.js
- src/pages/TransactionPage/TransactionPage.js
- src/pages/UserPage/UserPage.js
`user/myorder/:id`為路由
components 是 `SingleTransaction`
畫面刻完了，api 也串了，但因為目前 `getOneOrder` 打回來不會收到產品明細，
已經跟維尼討論怎麼辦了。
所以目前 single transaction 裡面的 商品是寫死的！
其他功能都完成！
> Transation order detail

- src/hooks/productHooks/useSearchProducts.js
- src/pages/SearchPage/SearchPage.js
- src/pages/SearchPage/components/SearchContextProduct.js
- src/pages/SearchPage/components/SearchItem.js
fix.search頁面改成四個一行，修復flex一行不齊跑版，分頁更改
> fix.search頁面改成四個一行，修復flex一行不齊跑版，分頁更改

- src/hooks/productHooks/useFindHotProducts.js
- src/hooks/productHooks/useFindNewProducts.js
- src/pages/HotProductsPage/components/ProductsSection.js
- src/pages/NewProductsPage/components/ProductsSection.js
fix.newProducts hotProducts新增加入購物車功能
> fix.newProducts hotProducts新增加入購物車功能

- src/pages/SearchPage/SearchPage.js
fix.PageBtn usePagination useSearchProducts 添加回來
> fix.PageBtn usePagination useSearchProducts 添加回來

- src/hooks/carts/useRecommendsApi.js
- src/pages/ProductsPage/components/ProductsSection.js
> Co fix bug

- src/pages/LoginPage/LoginPage.js
- src/pages/RegisterPage/RegisterPage.js
> fix.login register刪除FB註冊跟登入

- src/hooks/productHooks/useFindHotProducts.js
- src/hooks/productHooks/useFindNewProducts.js
- src/hooks/productHooks/useHotProducts.js
fix.newproducts hotproducts新增loading
> fix.newproducts hotproducts新增loading

- .vercel/README.txt
- .vercel/project.json
- src/hooks/carts/useShipping.js
- src/hooks/discountHooks/useDiscount.js
- src/hooks/productHooks/useAddProduct.js
- src/hooks/productHooks/useUpdateProduct.js
- src/pages/CartPage/component/RenderShippingForm.js
- src/pages/SingleTransactionPage/SingleTransactionPage.js
- src/pages/discountPages/TdContext.js
> Fix transaction

- public/index.html
- src/API/WEBAPI.js
- src/components/App/App.js
- src/components/routes/ProtectedRoutes.js
- src/hooks/carts/useAddCartItems.js
- src/hooks/carts/useCartApi.js
- src/hooks/carts/useGetSingleProduct.js
- src/hooks/carts/useRecommendsApi.js
- src/hooks/carts/useShippingApi.js
- src/hooks/orders/useFIndAllOrder.js
- src/hooks/orders/useOneOrder.js
- src/hooks/productHooks/useAddProduct.js
- src/hooks/productHooks/useAdminProducts.js
- src/hooks/productHooks/useAdminRestoreProducts.js
- src/hooks/productHooks/useFindHotProducts.js
- src/hooks/productHooks/useFindNewProducts.js
- src/hooks/productHooks/useFindProducts.js
- src/hooks/productHooks/useSearchProducts.js
- src/hooks/productHooks/useUpdateProduct.js
- src/hooks/user/useLogin.js
- src/hooks/user/useRegister.js
- src/hooks/user/useSingleTransaction.js
- src/hooks/user/useTransaction.js
- src/hooks/user/useUpadtePassword.js
- src/hooks/user/useUpdateUserInfo.js
> fix.title改變 WEBAPI放進API資料夾中

- src/hooks/carts/shipping/errorMessenger.js
- src/pages/CartPage/component/RenderShippingForm.js
> fix create-order-error-dealing

- src/components/Header/Header.js
cart 還沒登入不應存在 header 故調整 rwd 的顯示
> fix-rwd-header
